# Welcome to Jekyll!
#

# Site settings
title: Personal Navigation
description: |
  PNav website created  
  to help your nav needs
owner: Jack M. Taylor # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: jtaylor@emeraldcave.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jitb0824.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/JackInTheBox824
  github: https://github.com/JITB0824
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/JackInTheBox0824
  google-plus-square: https://plus.google.com/106006784390601096780/about/p/pub
  email: /contact/ jtaylor@emeraldcave.net
  #flickr:
  instagram: https://www.instagram.com/jackinthebox824/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
